# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Kien Malarney
tagline:             ''
description:         ''
url:                 http://kienma.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
name:              Kien Malarney
email:             malarneyk@gmail.com

# Custom vars
version:             1.0.0
